-- Initial database schema for Clinic Booking Manager.

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_clients_email UNIQUE (email)
);

CREATE TABLE doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    specialization VARCHAR(120) NOT NULL,
    email VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_doctors_email UNIQUE (email)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    duration_minutes INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_services_name UNIQUE (name),
    CONSTRAINT chk_services_duration_positive CHECK (duration_minutes > 0),
    CONSTRAINT chk_services_price_non_negative CHECK (price >= 0)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    appointment_start TIMESTAMP NOT NULL,
    appointment_end TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMP,

    CONSTRAINT fk_appointments_client
        FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT fk_appointments_service
        FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT chk_appointments_time_order
        CHECK (appointment_end > appointment_start),
    CONSTRAINT chk_appointments_status
        CHECK (status IN ('PLANNED', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_appointments_client_id ON appointments(client_id);
CREATE INDEX idx_appointments_doctor_id ON appointments(doctor_id);
CREATE INDEX idx_appointments_service_id ON appointments(service_id);
CREATE INDEX idx_appointments_start ON appointments(appointment_start);